package com.ronald.agent.example;

import com.ronald.agent.subagent.route.DefaultPromptRoutableAgent;
import com.ronald.agent.subagent.route.RoutableSubAgent;
import com.ronald.agent.subagent.route.SimpleRouteFallbackAgent;
import com.ronald.agent.workflow.AgenticWorkflow;
import com.ronald.agent.workflow.ConditionalAgentRouter;
import lombok.RequiredArgsConstructor;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.stereotype.Service;

/**
 * Demonstrates a conditional routing workflow using {@link ConditionalAgentRouter}.
 * <p>
 * Incoming user messages are classified by an LLM router and dispatched to the most
 * appropriate specialist agent (BILLING, TECH, or ACCOUNT). Unrecognised messages are
 * handled by a lightweight fallback that requires no LLM call.
 * </p>
 */
@Service
@RequiredArgsConstructor
public class ConditionalWorkflowExample {

    private final ChatClient chatClient;

    /**
     * Routes a user message to the appropriate specialist agent and returns its response.
     * <p>Routing categories:</p>
     * <ul>
     *   <li><b>BILLING</b>  – invoices and refund requests.</li>
     *   <li><b>TECH</b>     – bug reports and technical issues.</li>
     *   <li><b>ACCOUNT</b>  – login, password, and profile management.</li>
     *   <li><b>fallback</b> – any message that does not match a known category.</li>
     * </ul>
     *
     * @param userInput the raw message from the user
     * @return the response generated by the matched specialist agent (or the fallback)
     */
    public String route(String userInput) {
        RoutableSubAgent<String> billingHandler = DefaultPromptRoutableAgent.builder()
                .chatClient(chatClient)
                .routeKey("BILLING")
                .systemPrompt("You are a billing expert. Focus only on invoices and refunds.")
                .promptTemplate("Help the user with this billing request: {input}")
                .build();

        RoutableSubAgent<String> techHandler = DefaultPromptRoutableAgent.builder()
                .chatClient(chatClient)
                .routeKey("TECH")
                .systemPrompt("You are a senior IT engineer. Help users with technical bugs.")
                .promptTemplate("Resolve this technical issue: {input}")
                .build();

        RoutableSubAgent<String> accountHandler = DefaultPromptRoutableAgent.builder()
                .chatClient(chatClient)
                .routeKey("ACCOUNT")
                .systemPrompt("You are an account specialist. Help users with logins, passwords, and profiles.")
                .promptTemplate("Assist the user with this account request: {input}")
                .build();

        AgenticWorkflow<String> workflow = ConditionalAgentRouter.<String>builder()
                .routingClient(chatClient)
                .addRoute(billingHandler)
                .addRoute(techHandler)
                .addRoute(accountHandler)
                .defaultAgent(new SimpleRouteFallbackAgent()) // LLM-free fallback for unrecognized categories
                .build();

        return workflow.invoke(userInput);
    }
}