package com.ronald.agent.example;

import com.ronald.agent.subagent.DefaultPromptSubAgent;
import com.ronald.agent.workflow.IterativeRefinementWorkflow;
import lombok.RequiredArgsConstructor;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.stereotype.Service;

/**
 * Demonstrates an iterative refinement workflow using {@link IterativeRefinementWorkflow}.
 * <p>
 * An initial story draft is first generated by the chat client, then repeatedly refined
 * by a specialist agent until the content satisfies all supplied evaluation criteria
 * or the maximum number of attempts is reached.
 * </p>
 */
@Service
@RequiredArgsConstructor
public class IterativeRefinementWorkflowExample {

    private final ChatClient chatClient;

    /**
     * Generates and iteratively refines content based on the supplied task and criteria.
     * <ol>
     *   <li>An initial draft is produced directly via the chat client.</li>
     *   <li>An {@link IterativeRefinementWorkflow} repeatedly improves the draft until it
     *       passes evaluation against {@code criteria} or the attempt limit is reached.</li>
     * </ol>
     *
     * @param userInput the original user task (e.g. "Create a short story for children.")
     * @param criteria  the quality criteria the final content must satisfy
     * @return the refined content string
     */
    public String refineContent(String userInput, String criteria) {
        DefaultPromptSubAgent refinerAgent = DefaultPromptSubAgent.builder()
                .chatClient(chatClient)
                .outputKey("refinedContent")
                .systemPrompt("""
                        You are a storyteller expert specializing in refining children's stories.
                        When the current story content exists and there is feedback, refine the story to address the feedback and better meet the criteria.
                        """)
                .promptTemplate("""
                        Original task: {input}
                        Current story draft: {content}
                        Evaluation feedback: {feedback}
                        
                        Focus on making it fun, imaginative, and suitable for children. Keep the story concise and ensure it includes all required elements.
                        """)
                .build();

        String story = chatClient.prompt(userInput)
                .system("""
                        You are a creative storyteller specializing in children's stories.
                        
                        Create a fun, imaginative, and concise story suitable for children based on user input.
                        Ensure the story includes all required elements and meets the specified criteria provided by the input.
                        """)
                .call().content();

        // Build the iterative refinement workflow
        IterativeRefinementWorkflow workflow = IterativeRefinementWorkflow.builder()
                .evaluatorAgent(chatClient)
                .refinerAgent(refinerAgent)
                .initialContent(story)
                .criteria(criteria)
                .maxAttempts(7)
                .build();

        // Execute the workflow directly
        return workflow.invoke(userInput);
    }
}